version: '2'

services:
    server:
        depends_on:
            - mongodb
        container_name: server
        build: ./
        restart: unless-stopped
        ports:
            - '4000:4000'
        environment:
            - DB_HOST=mongodb
        image: ncioo/steadycontrol-server:latest

    mongodb:
        image: mongo:latest
        container_name: database
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - ./archive.gz:/archive.gz
            - db:/data/db
volumes:
    db:
    